### ISSUE TITLE
History rewritten?

### ISSUE THREAD

**Issue by reentim** [imagekit-developer/gem#2]
Our Gemfile.lock has been pointing to imagekit-gem since May 2019:

```
GIT
  remote: https://github.com/imagekit-developer/imagekit-gem.git
  revision: 5e49535cf6e9055c94d2b632041af766339141bb
  specs:
    imagekit (0.1.0)
      rest-client
```

That revision no longer exists in the repository... actually, the oldest commit dates to Jan 22, 2020.

Is using the GitHub gem source per the README still the best way to install imagekit-gem?

**Comment by imagekitio** [comment]
We will be releasing a new version of this gem this month.
